### ISSUE TITLE
Talon FX Support

### ISSUE THREAD

**Issue by CJBuchel** [wml-frc/WML#26]
Similar if not exactly the same as the spark max. But it has a higher tick count per rotation. 

Its used for the falcon 500. Uses integrated encoder and integrated motor controller (Talon FX) powered over PWM & CAN.

Curtin is using PWM. & maybe CAN. Probably try to make support for both.

**Comment by met4000** [comment]
Is this still a thing? Didn't I actually get around to doing this at some point?

**Comment by CJBuchel** [comment]
Nope, we never got the falcons so we never got a chance to build/ test it.
