### ISSUE TITLE
Error Controller Feedback

### ISSUE THREAD

**Issue by CJBuchel** [wml-frc/WML#43]
Above ^

**Comment by met4000** [comment]
?

**Comment by CJBuchel** [comment]
Yes

**Comment by met4000** [comment]
... what is it?

**Comment by CJBuchel** [comment]
I had a thought to implement vibration feedback on errors and stuff. But then i realized.... well, to difficult and vague. And if we needed errors specific to the robot. Or any type of feedback (flywhel is at the desired speed). Then it's better for us to just program it directly instead rather than try to add something like that to the lib

**Comment by met4000** [comment]
> it's better for us to just program it directly instead rather than try to add something like that to the lib

is the correct response
